## Imports

In [1]:
#Importing necessary dependencies
import pandas as pd
import geopandas as gpd
from shapely import wkt

In [2]:
#Importing dataframes
commute = pd.read_csv('../../../data/clean/commute_demographics.csv')
education = pd.read_csv('../../../data/clean/education_demographics.csv')
income = pd.read_csv('../../../data/clean/income_demographics.csv')
internet = pd.read_csv('../../../data/clean/internet_demographics.csv')
population = pd.read_csv('../../../data/clean/population_demographics.csv')

## Looking over commute

In [3]:
#Looking over commute data
commute.head()

,geoid,qualifying name,current land area (sq. m),current water area (sq. m),average commute to work (in min),workers 16 years and over,"workers 16 years and over: car, truck, or van",workers 16 years and over: drove alone,workers 16 years and over: carpooled,workers 16 years and over: public transportation (includes taxicab),...,occupied housing units: 4 vehicles available,occupied housing units: 5 or more vehicles available,renter-occupied housing units,renter-occupied housing units: no vehicle available,renter-occupied housing units: 1 vehicle available,renter-occupied housing units: 2 vehicles available,renter-occupied housing units: 3 vehicles available,renter-occupied housing units: 4 vehicles available,renter-occupied housing units: 5 or more vehicles available,geometry
0,17031823303,"Census Tract 8233.03, Cook County, Illinois",2008920,0,33.0,2224,1914,1655,259,106,...,66,0,510,80,337,93,0,0,0,"POLYGON ((-87.720963 41.683952, -87.720304 41...."
1,17031823304,"Census Tract 8233.04, Cook County, Illinois",3553267,0,31.0,2650,2186,1877,309,137,...,72,20,1178,157,772,167,79,3,0,MULTIPOLYGON (((-87.72003618903081 41.68396731...
2,17031740400,"Census Tract 7404, Cook County, Illinois",2838804,0,32.0,2399,2174,2099,75,107,...,24,15,494,31,343,120,0,0,0,"POLYGON ((-87.72008 41.691274, -87.719372 41.6..."
3,17031740300,"Census Tract 7403, Cook County, Illinois",1320728,0,33.0,2430,2202,2104,98,66,...,67,8,194,0,67,127,0,0,0,"POLYGON ((-87.720431 41.698569, -87.720066 41...."
4,17031822802,"Census Tract 8228.02, Cook County, Illinois",1305003,0,32.0,1639,1425,1386,39,80,...,33,103,85,26,32,27,0,0,0,"MULTIPOLYGON (((-87.720752 41.702042, -87.7207..."

## Income

In [10]:
incomemer = income.iloc[:,1:25]
incomemer = incomemer.drop(columns =['current land area (sq. m)','current water area (sq. m)'])
incomemer

,qualifying name,civilian population in labor force 16 years and over,civilian population in labor force 16 years and over: employed,civilian population in labor force 16 years and over: unemployed,total households reporting income,"households: less than $10,000","households: $10,000 to $14,999","households: $15,000 to $19,999","households: $20,000 to $24,999","households: $25,000 to $29,999",...,"households: $40,000 to $44,999","households: $45,000 to $49,999","households: $50,000 to $59,999","households: $60,000 to $74,999","households: $75,000 to $99,999","households: $100,000 to $124,999","households: $125,000 to $149,999","households: $150,000 to $199,999","households: $200,000 or more",gini index
0,"Census Tract 8233.03, Cook County, Illinois",2390,2271,119,1617,152,9,3,53,145,...,55,76,32,111,327,245,108,56,113,0.3864
1,"Census Tract 8233.04, Cook County, Illinois",3063,2688,375,2634,307,94,118,181,66,...,163,87,306,270,303,190,73,47,149,0.4889
2,"Census Tract 7404, Cook County, Illinois",2613,2416,197,1883,42,9,48,8,26,...,156,40,242,177,172,247,257,197,209,0.3553
3,"Census Tract 7403, Cook County, Illinois",2602,2468,134,1939,16,0,0,29,27,...,39,19,40,295,231,157,236,480,257,0.3026
4,"Census Tract 8228.02, Cook County, Illinois",1808,1652,156,1281,17,14,15,31,47,...,98,85,116,102,92,82,227,115,171,0.3995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
864,"Census Tract 3204, Cook County, Illinois",1644,1455,189,773,97,0,0,0,0,...,0,0,26,59,49,95,36,98,299,0.5470
865,"Census Tract 3201.01, Cook County, Illinois",5543,5297,246,4937,123,0,90,0,132,...,154,38,211,87,946,801,603,260,1407,0.5839
866,"Census Tract 814.03, Cook County, Illinois",6917,6708,209,6149,356,309,59,51,110,...,147,41,406,315,916,834,224,911,1374,0.4812
867,"Census Tract 814.02, Cook County, Illinois",3438,3262,176,3322,355,43,18,84,21,...,91,73,149,145,188,342,198,303,1215,0.5280
868,"Census Tract 9900, Cook County, Illinois",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN

## Commute + Income and GINI INDEX

In [11]:
cominc = commute.merge(incomemer, on='qualifying name')
cominc.sort_values(by='gini index', ascending = False)

,geoid,qualifying name,current land area (sq. m),current water area (sq. m),average commute to work (in min),workers 16 years and over,"workers 16 years and over: car, truck, or van",workers 16 years and over: drove alone,workers 16 years and over: carpooled,workers 16 years and over: public transportation (includes taxicab),...,"households: $40,000 to $44,999","households: $45,000 to $49,999","households: $50,000 to $59,999","households: $60,000 to $74,999","households: $75,000 to $99,999","households: $100,000 to $124,999","households: $125,000 to $149,999","households: $150,000 to $199,999","households: $200,000 or more",gini index
472,17031280900,"Census Tract 2809, Cook County, Illinois",114689,0,40.0,489,248,214,34,92,...,8,0,10,19,29,28,12,9,83,0.7401
679,17031060500,"Census Tract 605, Cook County, Illinois",228276,0,34.0,571,179,165,14,183,...,0,4,41,61,19,13,30,36,142,0.7257
454,17031252101,"Census Tract 2521.01, Cook County, Illinois",827450,24575,45.0,396,279,240,39,79,...,32,41,11,110,13,25,10,6,18,0.7244
330,17031380200,"Census Tract 3802, Cook County, Illinois",215130,0,33.0,584,279,235,44,196,...,51,22,58,113,16,0,32,57,30,0.7130
324,17031351400,"Census Tract 3514, Cook County, Illinois",323957,0,36.0,461,108,93,15,271,...,20,28,0,22,111,4,0,22,18,0.7107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,17031835800,"Census Tract 8358, Cook County, Illinois",284425,0,35.0,905,449,397,52,377,...,52,24,16,110,213,99,40,38,0,0.2806
175,17031980100,"Census Tract 9801, Cook County, Illinois",2981781,0,NaN,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
302,17031381700,"Census Tract 3817, Cook County, Illinois",196802,0,NaN,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
816,17031980000,"Census Tract 9800, Cook County, Illinois",19890200,92402,NaN,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
868,17031990000,"Census Tract 9900, Cook County, Illinois",0,1717072182,NaN,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN

## Creating csv file for Commute ##

In [17]:
commute.head()

,geoid,qualifying name,current land area (sq. m),current water area (sq. m),average commute to work (in min),workers 16 years and over,"workers 16 years and over: car, truck, or van",workers 16 years and over: drove alone,workers 16 years and over: carpooled,workers 16 years and over: public transportation (includes taxicab),...,occupied housing units: 4 vehicles available,occupied housing units: 5 or more vehicles available,renter-occupied housing units,renter-occupied housing units: no vehicle available,renter-occupied housing units: 1 vehicle available,renter-occupied housing units: 2 vehicles available,renter-occupied housing units: 3 vehicles available,renter-occupied housing units: 4 vehicles available,renter-occupied housing units: 5 or more vehicles available,geometry
0,17031823303,"Census Tract 8233.03, Cook County, Illinois",2008920,0,33.0,2224,1914,1655,259,106,...,66,0,510,80,337,93,0,0,0,"POLYGON ((-87.720963 41.683952, -87.720304 41...."
1,17031823304,"Census Tract 8233.04, Cook County, Illinois",3553267,0,31.0,2650,2186,1877,309,137,...,72,20,1178,157,772,167,79,3,0,MULTIPOLYGON (((-87.72003618903081 41.68396731...
2,17031740400,"Census Tract 7404, Cook County, Illinois",2838804,0,32.0,2399,2174,2099,75,107,...,24,15,494,31,343,120,0,0,0,"POLYGON ((-87.72008 41.691274, -87.719372 41.6..."
3,17031740300,"Census Tract 7403, Cook County, Illinois",1320728,0,33.0,2430,2202,2104,98,66,...,67,8,194,0,67,127,0,0,0,"POLYGON ((-87.720431 41.698569, -87.720066 41...."
4,17031822802,"Census Tract 8228.02, Cook County, Illinois",1305003,0,32.0,1639,1425,1386,39,80,...,33,103,85,26,32,27,0,0,0,"MULTIPOLYGON (((-87.720752 41.702042, -87.7207..."

In [18]:
commute_demos_copy = commute.copy(deep=True)
commute_demos_copy.set_index('geoid',inplace=True)

old_columns = ['occupied housing units: no vehicle available',
 'occupied housing units: 1 vehicle available',
 'occupied housing units: 2 vehicles available',
 'occupied housing units: 3 vehicles available',
 'occupied housing units: 4 vehicles available',
 'occupied housing units: 5 or more vehicles available']

new_columns = ['Percent Owner and Renter Occupied Housing: No Vehicles',
 'Percent Owner and Renter Occupied Housing: 1 Vehicle',
 'Percent Owner and Renter Occupied Housing: 2 Vehicles',
 'Percent Owner and Renter Occupied Housing: 3 Vehicles',
 'Percent Owner and Renter Occupied Housing: 4 Vehicles',
 'Percent Owner and Renter Occupied Housing: 5 or More Vehicles']

for i in range(1,len(new_columns)+1):
    #print(i)
    commute_demos_copy[new_columns[i-1]] = commute_demos_copy[old_columns[i-1]]/commute_demos_copy['occupied housing units']

In [19]:
old_columns2 = ['renter-occupied housing units: no vehicle available',
 'renter-occupied housing units: 1 vehicle available',
 'renter-occupied housing units: 2 vehicles available',
 'renter-occupied housing units: 3 vehicles available',
 'renter-occupied housing units: 4 vehicles available',
 'renter-occupied housing units: 5 or more vehicles available']

new_columns2 = ['Percent Renter-Occupied Housing: No Vehicles',
 'Percent Renter-Occupied Housing: 1 Vehicle',
 'Percent Renter-Occupied Housing: 2 Vehicles',
 'Percent Renter-Occupied Housing: 3 Vehicles',
 'Percent Renter-Occupied Housing: 4 Vehicles',
 'Percent Renter-Occupied Housing: 5 or More Vehicles']

for i in range(1,len(new_columns2)+1):
    #print(i)
    commute_demos_copy[new_columns2[i-1]] = commute_demos_copy[old_columns2[i-1]]/commute_demos_copy['renter-occupied housing units']

In [20]:
old_columns3 = ['workers 16 years and over: car, truck, or van',
               'workers 16 years and over: drove alone',
               'workers 16 years and over: carpooled',
               'workers 16 years and over: public transportation (includes taxicab)',
               'workers 16 years and over: motorcycle',
               'workers 16 years and over: bicycle',
               'workers 16 years and over: walked',
               'workers 16 years and over: other means']

new_columns3 = ['Percent Workers 16+: Car, Truck, or Van ',
                 'Percent Workers 16+: Drove Alone',
                 'Percent Workers 16+: Carpooled',
                 'Percent Workers 16+: Public Transportation (Includes Taxi)',
                 'Percent Workers 16+: Motorcycle',
                 'Percent Workers 16+: Bicycle',
                'Percent Workers 16+: Walked',
                'Percent Workers 16+: Other Means']

for i in range(1,len(new_columns3)+1):
    #print(i)
    commute_demos_copy[new_columns3[i-1]] = commute_demos_copy[old_columns3[i-1]]/commute_demos_copy['workers 16 years and over']

In [21]:
commute_demos = commute_demos_copy[['qualifying name',
                                    'geometry',
                                    'average commute to work (in min)',
                                    'occupied housing units',
                                    'Percent Owner and Renter Occupied Housing: No Vehicles',
                                     'Percent Owner and Renter Occupied Housing: 1 Vehicle',
                                     'Percent Owner and Renter Occupied Housing: 2 Vehicles',
                                     'Percent Owner and Renter Occupied Housing: 3 Vehicles',
                                     'Percent Owner and Renter Occupied Housing: 4 Vehicles',
                                     'Percent Owner and Renter Occupied Housing: 5 or More Vehicles',
                                    'renter-occupied housing units',
                                    'Percent Renter-Occupied Housing: No Vehicles',
                                     'Percent Renter-Occupied Housing: 1 Vehicle',
                                     'Percent Renter-Occupied Housing: 2 Vehicles',
                                     'Percent Renter-Occupied Housing: 3 Vehicles',
                                     'Percent Renter-Occupied Housing: 4 Vehicles',
                                     'Percent Renter-Occupied Housing: 5 or More Vehicles',
                                    'workers 16 years and over',
                                    'Percent Workers 16+: Car, Truck, or Van ',
                                     'Percent Workers 16+: Drove Alone',
                                     'Percent Workers 16+: Carpooled',
                                     'Percent Workers 16+: Public Transportation (Includes Taxi)',
                                     'Percent Workers 16+: Motorcycle',
                                     'Percent Workers 16+: Bicycle',
                                    'Percent Workers 16+: Walked',
                                    'Percent Workers 16+: Other Means']]

In [22]:
commute_demos

,qualifying name,geometry,average commute to work (in min),occupied housing units,Percent Owner and Renter Occupied Housing: No Vehicles,Percent Owner and Renter Occupied Housing: 1 Vehicle,Percent Owner and Renter Occupied Housing: 2 Vehicles,Percent Owner and Renter Occupied Housing: 3 Vehicles,Percent Owner and Renter Occupied Housing: 4 Vehicles,Percent Owner and Renter Occupied Housing: 5 or More Vehicles,...,Percent Renter-Occupied Housing: 5 or More Vehicles,workers 16 years and over,"Percent Workers 16+: Car, Truck, or Van",Percent Workers 16+: Drove Alone,Percent Workers 16+: Carpooled,Percent Workers 16+: Public Transportation (Includes Taxi),Percent Workers 16+: Motorcycle,Percent Workers 16+: Bicycle,Percent Workers 16+: Walked,Percent Workers 16+: Other Means
geoid,,,,,,,,,,,,,,,,,,,,,
17031823303,"Census Tract 8233.03, Cook County, Illinois","POLYGON ((-87.720963 41.683952, -87.720304 41....",33.0,1617,0.053185,0.332096,0.454545,0.119357,0.040816,0.000000,...,0.0,2224,0.860612,0.744155,0.116457,0.047662,0.0,0.000000,0.031025,0.008094
17031823304,"Census Tract 8233.04, Cook County, Illinois",MULTIPOLYGON (((-87.72003618903081 41.68396731...,31.0,2634,0.101367,0.497342,0.236143,0.130220,0.027335,0.007593,...,0.0,2650,0.824906,0.708302,0.116604,0.051698,0.0,0.000000,0.015472,0.026038
17031740400,"Census Tract 7404, Cook County, Illinois","POLYGON ((-87.72008 41.691274, -87.719372 41.6...",32.0,1883,0.041954,0.380775,0.437600,0.118959,0.012746,0.007966,...,0.0,2399,0.906211,0.874948,0.031263,0.044602,0.0,0.000000,0.007920,0.004585
17031740300,"Census Tract 7403, Cook County, Illinois","POLYGON ((-87.720431 41.698569, -87.720066 41....",33.0,1939,0.023208,0.324394,0.526560,0.087158,0.034554,0.004126,...,0.0,2430,0.906173,0.865844,0.040329,0.027160,0.0,0.009465,0.000000,0.000000
17031822802,"Census Tract 8228.02, Cook County, Illinois","MULTIPOLYGON (((-87.720752 41.702042, -87.7207...",32.0,1281,0.092116,0.197502,0.512881,0.091335,0.025761,0.080406,...,0.0,1639,0.869433,0.845638,0.023795,0.048810,0.0,0.000000,0.001830,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17031320400,"Census Tract 3204, Cook County, Illinois","POLYGON ((-87.627636 41.882057, -87.627594 41....",19.0,773,0.394567,0.486417,0.111255,0.007762,0.000000,0.000000,...,0.0,1372,0.166910,0.150875,0.016035,0.134840,0.0,0.000000,0.417638,0.003644
17031320101,"Census Tract 3201.01, Cook County, Illinois","POLYGON ((-87.620855 41.881881, -87.620825 41....",25.0,4937,0.305651,0.544055,0.150294,0.000000,0.000000,0.000000,...,0.0,5315,0.280903,0.272437,0.008467,0.105174,0.0,0.019567,0.278645,0.038758
17031081403,"Census Tract 814.03, Cook County, Illinois","MULTIPOLYGON (((-87.624311 41.889115, -87.6243...",22.0,6149,0.527891,0.367865,0.104245,0.000000,0.000000,0.000000,...,0.0,6652,0.253608,0.240379,0.013229,0.186861,0.0,0.010523,0.306975,0.053367
17031081402,"Census Tract 814.02, Cook County, Illinois","POLYGON ((-87.617537 41.893453, -87.617164 41....",27.0,3322,0.329621,0.555388,0.105659,0.004214,0.005117,0.000000,...,0.0,3246,0.374615,0.362908,0.011707,0.186075,0.0,0.012939,0.253235,0.012939
17031990000,"Census Tract 9900, Cook County, Illinois","MULTIPOLYGON (((-87.609113 41.888267, -87.6054...",NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### FINAL CSV

In [23]:
commute_demos.to_csv('../../../data/final_data/commute_demos.csv')